[hub.server]

# offline = [scarlet]\u{26A0} Offline
# online = [white]\u{E837} [accent]Players: {0}\n[white]\u{E827} [accent]Map: {1}
# online.full = [white]\u{E837} [accent]Players: {0}\n[white]\u{E827} [accent]Map: {1}\n[white]\u{E871} [accent]Wave: {2}\n[white]\u{E875} [accent]Address: {3}

online.players = [white]\u{E837} [accent]Players: {players}
online.map     = [white]\u{E827} [accent]Map: {map}
online.wave    = [white]\u{E871} [accent]Wave: {wave}
online.address = [white]\u{E875} [accent]Address: {address}

offline = [scarlet]\u{26A0} Offline
map = [white]

error = [scarlet]Failed to connect to {host}
      =
      = Error: [white](please report this on [blue]/discord[] if the issue persists)[]
      = {error}